### PR TITLE
build: syncplay version `1.7.3`

### PR DESCRIPTION
**Pull request by Misaka13514**

### CODE REVIEW

**Comment by dnomd343** [comment]
The docker image will be built and pushed later.

**Comment by dnomd343** [comment]
The image has been updated on DockerHub, thanks to @Misaka13514 .

**Comment by Misaka13514** [comment]
Thank you! I can write a GitHub action (CI) to build Docker image automatically, would you like it?

**Comment by dnomd343** [comment]
Of course! PR is always welcome.

**Pull request merged**
